### ISSUE TITLE
Hang/no result from Pybots

### ISSUE THREAD

**Issue by cHJlaXpoZXI** [dhondta/pybots#1]
Hi !

Thanks for your module ! I want to use it for Root-me but I might not be working. This is the script I run :

```python

#!/usr/bin/python

import math
from pybots import RootMeIRCBot

with RootMeIRCBot(1, "root_me_username") as bot:
    bot.inputs['Message']

```
For now, my goal is to have the answer of the bot. But when I execute this script, I have the following error :

```python

Traceback (most recent call last):
  File "./rootme_irc2.py", line 7, in <module>
    bot.inputs['Message']
  File "/usr/local/lib/python2.7/dist-packages/pybots/base/template.py", line 122, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/pybots/specific/irc.py", line 59, in close
    super(IRCBot, self).close(exit)
TypeError: close() takes exactly 1 argument (2 given)
```
I cannot continue the challenge if I don't have the message from the bot. So I don't know if I use it correctly or not...

Thanks,
Regards,

**Comment by dhondta** [comment]
Hi @cHJlaXpoZXI ,
As the error suggests, you used an unexpected argument in your method call ; please replace your statement as follows :

```
super(IRCBot, self).close(exit)
```

This should be:

```
super(IRCBot, self).close()
```
